name: Go Application Build and Test

on:
  push:
    branches:
      - main
      - 'dev*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.20.4

      - name: Build application
        run: |
          set CGO_ENABLED=0
          set GOOS=windows
          set GOARCH=amd64
          go build -o build/endpoint main.go

      - name: Run tests
        run: go test ./...
